### ISSUE TITLE
Object is a reserved word as of PHP 7.2

### ISSUE THREAD

**Issue by scottrudy** [Learnosity/learnosity-qti#21]
The Assets Processing class located at src\Processors\QtiV2\In\Processings\AssetsProcessing.php has a reference to the qti-sdk qtism\data\content\xhtml\Object class which is now in conflict with a reserved work in PHP 7.2. I have opened an issue with the qti-sdk repo at oat-sa/qti-sdk#119

**Comment by ttton** [comment]
Now that qti-sdk has released 10.0.0 with support for PHP 7.2, we'll look into upgrading accordingly. At this stage we're aiming to have PHP 7.2 support from v1.0.1 onwards.

**Comment by scottrudy** [comment]
Is this any closer to being resolved? I've noticed that [PHP 5.x is now End of Life](http://php.net/supported-versions.php)

**Comment by ttton** [comment]
Hi @scottrudy, we've just released v1.1.0, which now includes support for PHP 7.2.

**Comment by scottrudy** [comment]
Do you have target date when that would be pushed to the composer package manager? Currently I still see 1.0.0 as the latest version.

**Comment by scottrudy** [comment]
This appears to be resolved as I can now run the latest version with PHP 7.2. Thanks.
